=== darktal91/tecweb/data/utenti/utenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  targetNamespace="http://www.imperofiere.com" elementFormDefault="qualified" xmlns="http://www.imperofiere.com" -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="utenti" type="Tutenti" />
    
  <xs:complexType name="Tutenti">
    <xs:sequence>
      <xs:element name="utente" maxOccurs="unbounded" type="Tutente" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Tutente">
    <xs:sequence>
      <xs:element name="nickname" type="xs:string" />
      <xs:element name="password" type="xs:string" />
      <xs:element name="nome" type="xs:string" />
      <xs:element name="cognome" type="xs:string" />
      <xs:element name="datanascita" type="xs:date" />
      <xs:element name="indirizzo" type="Tindirizzo" />
      <xs:element name="email" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Tindirizzo">
    <xs:sequence>
      <xs:element name="via" type="xs:string" />
      <xs:element name="numero" type="Tnumero" />
      <xs:element name="citta" type="xs:string" />
      <xs:element name="provincia" type="Tprovince" />
      <xs:element name="CAP" type="Tcap" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="Tnumero">
    <xs:restriction base="xs:integer">
      <xs:minExclusive value="0" />
    </xs:restriction>
  </xs:simpleType>
      
  <xs:simpleType name="Tprovince">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AG" />
      <xs:enumeration value="AL" />
      <xs:enumeration value="AN" />
      <xs:enumeration value="AO" />
      <xs:enumeration value="AR" />
      <xs:enumeration value="AP" />
      <xs:enumeration value="AT" />
      <xs:enumeration value="AV" />
      <xs:enumeration value="BA" />
      <xs:enumeration value="BT" />
      <xs:enumeration value="BL" />
      <xs:enumeration value="BN" />
      <xs:enumeration value="BG" />
      <xs:enumeration value="BI" />
      <xs:enumeration value="BO" />
      <xs:enumeration value="BZ" />
      <xs:enumeration value="BS" />
      <xs:enumeration value="BR" />
      <xs:enumeration value="CA" />
      <xs:enumeration value="CL" />
      <xs:enumeration value="CB" />
      <xs:enumeration value="CI" />
      <xs:enumeration value="CE" />
      <xs:enumeration value="CT" />
      <xs:enumeration value="CZ" />
      <xs:enumeration value="CH" />
      <xs:enumeration value="CO" />
      <xs:enumeration value="CS" />
      <xs:enumeration value="CR" />
      <xs:enumeration value="KR" />
      <xs:enumeration value="CN" />
      <xs:enumeration value="EN" />
      <xs:enumeration value="FM" />
      <xs:enumeration value="FE" />
      <xs:enumeration value="FI" />
      <xs:enumeration value="FG" />
      <xs:enumeration value="FC" />
      <xs:enumeration value="FR" />
      <xs:enumeration value="GE" />
      <xs:enumeration value="GO" />
      <xs:enumeration value="GR" />
      <xs:enumeration value="IM" />
      <xs:enumeration value="IS" />
      <xs:enumeration value="SP" />
      <xs:enumeration value="AQ" />
      <xs:enumeration value="LT" />
      <xs:enumeration value="LE" />
      <xs:enumeration value="LC" />
      <xs:enumeration value="LI" />
      <xs:enumeration value="LO" />
      <xs:enumeration value="LU" />
      <xs:enumeration value="MC" />
      <xs:enumeration value="MN" />
      <xs:enumeration value="MS" />
      <xs:enumeration value="MT" />
      <xs:enumeration value="ME" />
      <xs:enumeration value="MI" />
      <xs:enumeration value="MO" />
      <xs:enumeration value="MB" />
      <xs:enumeration value="NA" />
      <xs:enumeration value="NO" />
      <xs:enumeration value="NU" />
      <xs:enumeration value="OT" />
      <xs:enumeration value="OR" />
      <xs:enumeration value="PD" />
      <xs:enumeration value="PA" />
      <xs:enumeration value="PR" />
      <xs:enumeration value="PV" />
      <xs:enumeration value="PG" />
      <xs:enumeration value="PU" />
      <xs:enumeration value="PE" />
      <xs:enumeration value="PC" />
      <xs:enumeration value="PI" />
      <xs:enumeration value="PT" />
      <xs:enumeration value="PN" />
      <xs:enumeration value="PZ" />
      <xs:enumeration value="PO" />
      <xs:enumeration value="RG" />
      <xs:enumeration value="RA" />
      <xs:enumeration value="RC" />
      <xs:enumeration value="RE" />
      <xs:enumeration value="RI" />
      <xs:enumeration value="RN" />
      <xs:enumeration value="RM" />
      <xs:enumeration value="RO" />
      <xs:enumeration value="SA" />
      <xs:enumeration value="VS" />
      <xs:enumeration value="SS" />
      <xs:enumeration value="SV" />
      <xs:enumeration value="SI" />
      <xs:enumeration value="SR" />
      <xs:enumeration value="SO" />
      <xs:enumeration value="TA" />
      <xs:enumeration value="TE" />
      <xs:enumeration value="TR" />
      <xs:enumeration value="TO" />
      <xs:enumeration value="OG" />
      <xs:enumeration value="TP" />
      <xs:enumeration value="TN" />
      <xs:enumeration value="TV" />
      <xs:enumeration value="TS" />
      <xs:enumeration value="UD" />
      <xs:enumeration value="VA" />
      <xs:enumeration value="VE" />
      <xs:enumeration value="VB" />
      <xs:enumeration value="VC" />
      <xs:enumeration value="VR" />
      <xs:enumeration value="VV" />
      <xs:enumeration value="VI" />
      <xs:enumeration value="VT" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="Tcap">
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-9][0-9][0-9][0-9][0-9]" />
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== darktal91/tecweb/data/utenti.xml
<?xml version="1.0"?>
<!-- xmlns="http://www.imperofiere.com" xs:schemaLocation="http://www.imperofiere.com utenti.xsd" -->
<utenti xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="utenti.xsd">
	<utente>
		<nickname>admin</nickname>
		<password>d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892</password>
		<nome>admin</nome>
		<cognome>admin</cognome>
		<datanascita>1970-01-01</datanascita>
		<indirizzo>
			<via>admin</via>
			<numero>42</numero>
			<citta>admin</citta>
			<provincia>PD</provincia>
			<CAP>42042</CAP>
		</indirizzo>
		<email>admin@admin.it</email>
	</utente>
	<utente>
		<nickname>darktal91</nickname>
		<password>5205e90469a95a4d150b72f2ba5050de40a0a9541d8977c1e571ce5244ebbec4</password>
		<nome>andrea</nome>
		<cognome>cardin</cognome>
		<datanascita>1991-11-14</datanascita>
		<indirizzo>
			<via>ghiacciaia</via>
			<numero>20/2</numero>
			<citta>santa giustina in colle</citta>
			<provincia>PD</provincia>
			<CAP>35010</CAP>
		</indirizzo>
		<email>darktal91@gmail.com</email>
	</utente>
</utenti>
