=== darktal91/tecweb/data/eventi/eventi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns="http://www.imperofiere.com"
targetNamespace="http://www.imperofiere.com"
elementFormDefault="qualified" >
<xs:element name="eventi" type="TEventi" />
<xs:complexType name="TEventi">
	<xs:sequence>
      		<xs:element name="evento" maxOccurs="unbounded" type="TEvento" />
    	</xs:sequence>
</xs:complexType>
<xs:complexType name="TEvento">
	<xs:sequence>
			<xs:element name="titolo" type="xs:string"/>
      		<xs:element name="descrizione" type="xs:string" />
      		<xs:element name="foto" type="TFoto" minOccurs="0" maxOccurs="1"/>
    	</xs:sequence>
	<xs:attribute name="id" type="xs:string" use="required" />
</xs:complexType>
<xs:complexType name="TFoto">
	<xs:sequence>
		<xs:element name="img" maxOccurs="unbounded"  type="TImmagine" />
    	</xs:sequence>
</xs:complexType>
<xs:complexType name="TImmagine">
    	<xs:attribute name="src" type="xs:anyURI" use="required" />
    	<xs:attribute name="alt" type="xs:string" />
</xs:complexType>
</xs:schema>

=== darktal91/tecweb/data/utenti/eventi/eventi.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventi xmlns="http://www.empirecon.it" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:schemaLocation="http://www.empirecon.it eventi.xsd">
 <evento id="1">
	<titolo>L'estasi di Alderaan</titolo>
	<descrizione>Leia col bikini dorato è nell'immaginario collettivo una delle icone di sensualità nel mondo del cinema, in questo evento è possibile ammirare
	le cosplay di leia in bikini dorato.
	</descrizione>
	<foto>
		<img src="../image/leia-bikins.jpg" alt="Cosplay di Leia" />
	</foto>
 </evento>
 <evento id="2">
	<titolo>L'urlo dei mandaloriani</titolo>
	<descrizione>Sei un cosplay o amante degli affascinanti e misteriosi mandaloriani, allora non puoi perdere questo evento</descrizione>
	<foto>
		<img src="../image/mandalorians.jpg" alt="Cosplay in armatura mandaloriana" />
	</foto>
 </evento>
 <evento id="3">
	<titolo>La legione 501</titolo>
	<descrizione>La legione 501, detta il pugno di Vader, è la personale armata del potente Signore Oscuro, unisciti e ammira la riproduzione fatta dai cosplay
	 della celebre armata!</descrizione>
	<foto>
		<img src="../image/storm.jpg" alt="Cosplay stormtrooper" />
	</foto>
 </evento>
 <evento id="4">
	<titolo>Il potere dei sith</titolo>
	<descrizione>Potenti e tenebrosi, i sith sono i maggiori nemici dei cavalieri Jedi. Che aspetti? Entra e partecipa all'evento</descrizione>
	<foto>
		<img src="../image/sith.jpg" alt="Una sith" />
	</foto>
 </evento>
 <evento id="5">
	<titolo>La cantina di mos eisley</titolo>
	<descrizione>Celebre riproduzione della cantina presente in Star Wars IV: Una nuova speranza</descrizione>
	<foto>
		<img src="../image/cantina.png" alt="Riproduzione della cantina" />
	</foto>
 </evento>
 <evento id="6">
	<titolo>Area fumetti</titolo>
	<descrizione>I fumetti sono da sempre una delle punte di diamante del cosidetto Universo Espanso. In questo evento è possibile acquistare i migliori
	 fumetti dedicati alla saga e aggiornarsi sulle future uscite</descrizione>
 </evento>
 <evento id="7">
	<titolo>Action figure, che passione</titolo>
	<descrizione>In questa mostra potete ammirare e acquistare le action figures dell'universo di Star Wars</descrizione>
 </evento>
 <evento id="8">
	<titolo>La storia di Star Wars</titolo>
	<descrizione>Percorso guidato che illustrerà i punti salienti della esalogia di Star Wars, con un occhio alla serie tv Clone Wars</descrizione>
 </evento>
</eventi>
