=== darktal91/tecweb/data/biglietti/acquisti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.imperofiere.com" xmlns="http://www.imperofiere.com" elementFormDefault="qualified">
  
<xs:element name="acquisti" type="Tacquisti"/>

  <xs:complexType name="Tacquisti">
    <xs:sequence>
      <xs:element name="tipologia" maxOccurs="unbounded" type="Ttipologia" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Ttipologia">
    <xs:sequence>
      <xs:element name="acquisto" maxOccurs="unbounded" type="Tacquisto" />
    </xs:sequence>
    <xs:attributeGroup ref="Ttipologiattr"/>
  </xs:complexType>
  
  <xs:attributeGroup name="Ttipologiaattr">
    <xs:attribute name="tipo" type="Ttipo" use="required" />
    <xs:attribute name="prezzo" type="Tprezzo" use="required" />
  </xs:attributeGroup>

    <xs:simpleType name="Ttipo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="intero" />
      <xs:enumeration value="ridotto" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="Tprezzo">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="Tacquisto">
    <xs:attributeGroup ref="Tacquistoattr"/>
  </xs:complexType>

  <xs:attributeGroup name="Tacquistoattr">
    <xs:attribute name="username" type="Tusername" use="required" />
    <xs:attribute name="datatime" type="xs:dateTime" use="required" />
  </xs:attributeGroup>

  <!--
  TODO :
	  sistemare il tipo acquisto in Tacquisto
	  Definire il tipo username (simpleType?)
  
  -->
  
</xs:schema>

=== darktal91/tecweb/data/biglietti/acquisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="acquisti.xsl"?>
<d:acquisti xmlns="http://www.empirecon.it" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns:d="http://www.empirecon.it" xs:schemaLocation="http://www.enpirecon.it acquisti.xsd">

<tipologia id="intero" prezzo="25">
	<acquisto username="sydernee" datatime="2014-08-08T00-16-42">3</acquisto>
	<acquisto username="sydernee" datatime="2014-08-08T00-18-13">1</acquisto>
	<acquisto username="sydernee" datatime="2014-08-08T00-20-11">9</acquisto>
	<acquisto username="sydernee" datatime="2014-08-08T05-15-46">1</acquisto>
	<acquisto username="sydernee" datatime="2014-08-08T09-43-37">1</acquisto>
</tipologia>
  
<tipologia id="ridotto" prezzo="5">
	<acquisto username="sydernee" datatime="2014-08-08T00-19-57">6</acquisto>
	<acquisto username="sydernee" datatime="2014-08-08T00-20-23">2</acquisto>
</tipologia>

<tipologia id="gratis" prezzo="0">
	<acquisto username="sydernee" datatime="2014-08-08T00-20-39">4</acquisto>
	<acquisto username="sydernee" datatime="2014-08-08T05-06-32">3</acquisto>
	<acquisto username="sydernee" datatime="2014-08-08T05-07-57">1</acquisto>
</tipologia>
</d:acquisti>
