=== darktal91/tecweb/data/biglietti/biglietti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.imperofiere.com" xmlns="http://www.imperofiere.com" elementFormDefault="qualified">
  
<xs:element name="biglietti" type="Tbiglietti"/>
  
  <xs:complexType name="Tbiglietti">
    <xs:sequence>
      <xs:element name="biglietto" maxOccurs="unbounded" type="Tbiglietto" />
    </xs:sequence>
  </xs:complexType>
 
  <xs:complexType name="Tbiglietto">
    <xs:sequence>
      <xs:element name="qtatot" type="xs:unsignedInt" />
      <xs:element name="venduti" type="xs:unsignedInt" />
    </xs:sequence>
    <xs:attributeGroup ref="Tbigliettoattr"/>
  </xs:complexType>

  <xs:attributeGroup name="Tbigliettoattr">
    <xs:attribute name="tipo" type="Ttipo" use="required" />
    <xs:attribute name="prezzo" type="Tprezzo" use="required" />
  </xs:attributeGroup>
  
  <xs:simpleType name="Ttipo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="intero" />
      <xs:enumeration value="ridotto" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="Tprezzo">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  
  
  
  
</xs:schema>

=== darktal91/tecweb/data/biglietti/biglietti.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="biglietti.xsl"?> 
<biglietti xmlns:b="http://www.imperofiere.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.imperofiere.com biglietti.xsd">

  <biglietto tipo="intero" prezzo="10">
    <qtatot>123</qtatot>
    <venduti>26</venduti>
  </biglietto>
  
  <biglietto tipo="ridotto" prezzo="5">
    <qtatot>95</qtatot>
    <venduti>11</venduti>
  </biglietto>
  
  <biglietto tipo="Spam Side VIP" prezzo="2">
    <qtatot>42</qtatot>
    <venduti>42</venduti>
  </biglietto>
</biglietti>
