=== darktal91/tecweb/cgi-bin/commenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.imperofiere.com" elementFormDefault="qualified" xmlns="http://www.imperofiere.com">
  
  <xs:element name="commentbook" type="Tbook" />
  
  <xs:complexType name="Tbook">
    <xs:sequence>
      <xs:element name="commento" type="Tcommento" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Tcommento">
    <xs:sequence>
      <xs:element name="username" type="xs:string" />
      <xs:element name="datetime" type="xs:dateTime" />
      <xs:element name="testo" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== darktal91/tecweb/cgi-bin/commenti.xml
<?xml version="1.0"?>
<commentbook xmlns="http://www.imperofiere.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.imperofiere.com commenti.xsd">
  <commento>
    <username>Darth Carmine</username>
    <datetime>2014-03-12T13:20:01</datetime>
    <testo>WEE CHISTU SITU ME PIASCE ASSAJE</testo>
  </commento>
  <commento>
    <username>Luca Camminaciello</username>
    <datetime>2014-03-12T13:26:51</datetime>
    <testo>Mi fa male il polso</testo>
  </commento>
</commentbook>
